# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/get-started/connection-profiles

dbt_sipher:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: sipher-data-testing
      dataset: tmp_dbt
      location: US
      priority: interactive
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      keyfile: /opt/airflow/data/authentication/data-platform-387707-testing.json
      execution_project: data-platform-387707
      threads: 10
    production:
      type: bigquery
      project: sipher-data-platform
      dataset: dbt_sipher
      location: US
      priority: interactive
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      keyfile: /home/airflow/gcs/data/authentication/data-platform-387707-55e58e976bfa.json
      execution_project: data-platform-387707
      threads: 10
